route:
    receiver: devops/admin
receivers:
    - name: 'devops/admin'
      email_configs:
          - to: 'sergey.bityukov@bloomex.ca'
            from: 'alert@bloomex.ca'
            require_tls: false
            #auth_username: 'alertmanager'
            #auth_password: 'password'
            #auth_secret: 'secret'
            #auth_identity: 'identity'
            smarthost: 172.10.10.5:25
            send_resolved: true
