version: '3.7'
services:
  prometheus:
    container_name: promet01
    build: ./prometheus
    ports:
      - "83:9090"
    networks:
      monitoring:
        ipv4_address: 172.10.10.2
    command:
      - "--storage.tsdb.allow-overlapping-blocks"
    volumes:
      - type: volume
        source: prometheus_tsdb
        target: /prometheus
      - type: volume
        source: prometheus_conf
        target: /etc/prometheus
    restart: unless-stopped

  grafana:
    container_name: grafana01
    build: ./grafana
    ports:
      - "84:3000"
    networks:
      monitoring:
        ipv4_address: 172.10.10.3
    volumes:
      - type: volume
        source: grafana_db
        target: /var/lib/grafana
      - type: volume
        source: grafana_conf
        target: /etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped

  # alertmanager:
  #   container_name: alertmanager01
  #   build: ./alertmanager
  #   ports:
  #     - "85:9093"
  #   networks:
  #     monitoring:
  #       ipv4_address: 172.10.10.4
  #   volumes:
  #     - type: volume
  #       source: alertmanager-data
  #       target: /alertmanager
  #     - type: volume
  #       source: alertmanager_conf
  #       target: /etc/prometheus/alertmanager

  #   depends_on:
  #     - prometheus
  #   restart: unless-stopped
  #   command:
  #     - '--cluster.advertise-address=0.0.0.0:9093'

  # postfix:
  #   container_name: postfix01
  #   build: ./postfix
  #   ports:
  #     - "25:25"
  #   networks:
  #     monitoring:
  #       ipv4_address: 172.10.10.5
  #   volumes:
  #     - type: volume
  #       source: postfix_conf
  #       target: /etc/postfix
  #   depends_on:
  #     - alertmanager
  #   restart: unless-stopped
  #   command:
  #     - ' bloomex.ca'

networks:
   monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24



volumes:
  prometheus_tsdb:
  prometheus_conf:
  grafana_db:
  grafana_conf:
  # alertmanager-data:
  # alertmanager_conf:
  # postfix_conf:
