FROM ubuntu:22.04
MAINTAINER EdwardArutyunyan
LABEL prometheus_alertmanager=v1.1

# install alertmanager
RUN apt-get update \
&& apt -y install prometheus-alertmanager \
                  nano \
                  \
&& apt-get  -y clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# open port
expose 9093

# default workdir
WORKDIR /etc/prometheus/alertmanager/

# copy config
COPY alertmanager.yml .

# docker start
ENTRYPOINT [ "/bin/prometheus-alertmanager" ]
CMD        [ "--config.file=/etc/prometheus/alertmanager/alertmanager.yml" ]
